# Generated by Django 3.2.16 on 2024-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20241212_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Запланирован'),
        ),
    ]
